// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OauthCallbackParamsProvider.
const (
	Github OauthCallbackParamsProvider = "github"
	Google OauthCallbackParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the OauthCallbackParamsProvider enum.
func (e OauthCallbackParamsProvider) Valid() bool {
	switch e {
	case Github:
		return true
	case Google:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken The JWT access token to be used in the Authorization header
	AccessToken string `json:"accessToken"`

	// ExpiresIn Access token lifetime in seconds. The refresh token's lifetime is not exposed here — it lives in the HttpOnly cookie's Max-Age.
	ExpiresIn *int `json:"expiresIn,omitempty"`

	// TokenType The type of the token issued
	TokenType string `json:"tokenType"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MonitorCreateRequest defines model for MonitorCreateRequest.
type MonitorCreateRequest struct {
	PollIntervalSec *int   `json:"pollIntervalSec,omitempty"`
	Url             string `json:"url"`
}

// MonitorResponse defines model for MonitorResponse.
type MonitorResponse struct {
	Active          bool               `json:"active"`
	CheckedAt       time.Time          `json:"checkedAt"`
	Id              openapi_types.UUID `json:"id"`
	PollIntervalSec int                `json:"pollIntervalSec"`
	Url             string             `json:"url"`
}

// MonitorUpdateRequest defines model for MonitorUpdateRequest.
type MonitorUpdateRequest struct {
	Active          bool   `json:"active"`
	PollIntervalSec int    `json:"pollIntervalSec"`
	Url             string `json:"url"`
}

// SnapshotResponse defines model for SnapshotResponse.
type SnapshotResponse struct {
	Alive          bool               `json:"alive"`
	CheckedAt      time.Time          `json:"checkedAt"`
	Id             openapi_types.UUID `json:"id"`
	MonitorId      openapi_types.UUID `json:"monitorId"`
	ResponseSize   int                `json:"responseSize"`
	ResponseTimeMs int                `json:"responseTimeMs"`
	ServerName     *string            `json:"serverName,omitempty"`
	SslExpiresAt   *time.Time         `json:"sslExpiresAt,omitempty"`
	StatusCode     int                `json:"statusCode"`
}

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
}

// UserUpdateRequest defines model for UserUpdateRequest.
type UserUpdateRequest struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Password *string              `json:"password,omitempty"`
}

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	// Code Temporary authorization code from the OAuth provider
	Code string `form:"code" json:"code"`

	// State Security string
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// OauthCallbackParamsProvider defines parameters for OauthCallback.
type OauthCallbackParamsProvider string

// GetMonitorsParams defines parameters for GetMonitors.
type GetMonitorsParams struct {
	// Limit Maximum number of monitors to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of monitors to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetSnapshotsByMonitorIDParams defines parameters for GetSnapshotsByMonitorID.
type GetSnapshotsByMonitorIDParams struct {
	// Limit Maximum number of snapshots to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of snapshots to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// CreateMonitorJSONRequestBody defines body for CreateMonitor for application/json ContentType.
type CreateMonitorJSONRequestBody = MonitorCreateRequest

// UpdateMonitorJSONRequestBody defines body for UpdateMonitor for application/json ContentType.
type UpdateMonitorJSONRequestBody = MonitorUpdateRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreateRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// OauthCallback OAuth callback handler
	// (GET /auth/callback/{provider})
	OauthCallback(ctx echo.Context, provider OauthCallbackParamsProvider, params OauthCallbackParams) error
	// LoginUser Logs user into the system
	// (POST /auth/login)
	LoginUser(ctx echo.Context) error
	// LogoutUser Revoke the current refresh token and end the session
	// (POST /auth/logout)
	LogoutUser(ctx echo.Context) error
	// RefreshToken Rotate the refresh token and issue a new access token
	// (POST /auth/refresh)
	RefreshToken(ctx echo.Context) error
	// GetMonitors Get monitors for current user
	// (GET /monitors)
	GetMonitors(ctx echo.Context, params GetMonitorsParams) error
	// CreateMonitor Add object to monitor
	// (POST /monitors)
	CreateMonitor(ctx echo.Context) error
	// DeleteMonitor Delete a monitor
	// (DELETE /monitors/{id})
	DeleteMonitor(ctx echo.Context, id openapi_types.UUID) error
	// UpdateMonitor Update monitor configuration
	// (PATCH /monitors/{id})
	UpdateMonitor(ctx echo.Context, id openapi_types.UUID) error
	// GetSnapshotsByMonitorID Get snapshots by monitor ID
	// (GET /monitors/{id}/snapshots)
	GetSnapshotsByMonitorID(ctx echo.Context, id openapi_types.UUID, params GetSnapshotsByMonitorIDParams) error
	// CreateUser Create user
	// (POST /user)
	CreateUser(ctx echo.Context) error
	// UpdateUser Update user
	// (PATCH /user/{id})
	UpdateUser(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// OauthCallback converts echo context to params.
func (w *ServerInterfaceWrapper) OauthCallback(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "provider" -------------
	var provider OauthCallbackParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", ctx.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OauthCallbackParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", ctx.QueryParams(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", ctx.QueryParams(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OauthCallback(ctx, provider, params)
	return err
}

// LoginUser converts echo context to params.
func (w *ServerInterfaceWrapper) LoginUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LoginUser(ctx)
	return err
}

// LogoutUser converts echo context to params.
func (w *ServerInterfaceWrapper) LogoutUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LogoutUser(ctx)
	return err
}

// RefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshToken(ctx)
	return err
}

// GetMonitors converts echo context to params.
func (w *ServerInterfaceWrapper) GetMonitors(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMonitorsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMonitors(ctx, params)
	return err
}

// CreateMonitor converts echo context to params.
func (w *ServerInterfaceWrapper) CreateMonitor(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateMonitor(ctx)
	return err
}

// DeleteMonitor converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteMonitor(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteMonitor(ctx, id)
	return err
}

// UpdateMonitor converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateMonitor(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateMonitor(ctx, id)
	return err
}

// GetSnapshotsByMonitorID converts echo context to params.
func (w *ServerInterfaceWrapper) GetSnapshotsByMonitorID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSnapshotsByMonitorIDParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSnapshotsByMonitorID(ctx, id, params)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUser(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/user", wrapper.CreateUser, options.OperationMiddlewares["createUser"]...)
	router.PATCH(options.BaseURL+"/user/:id", wrapper.UpdateUser, options.OperationMiddlewares["updateUser"]...)
	router.POST(options.BaseURL+"/auth/login", wrapper.LoginUser, options.OperationMiddlewares["loginUser"]...)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken, options.OperationMiddlewares["refreshToken"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.LogoutUser, options.OperationMiddlewares["logoutUser"]...)
	router.GET(options.BaseURL+"/auth/callback/:provider", wrapper.OauthCallback, options.OperationMiddlewares["oauthCallback"]...)
	router.GET(options.BaseURL+"/monitors", wrapper.GetMonitors, options.OperationMiddlewares["getMonitors"]...)
	router.POST(options.BaseURL+"/monitors", wrapper.CreateMonitor, options.OperationMiddlewares["createMonitor"]...)
	router.DELETE(options.BaseURL+"/monitors/:id", wrapper.DeleteMonitor, options.OperationMiddlewares["deleteMonitor"]...)
	router.PATCH(options.BaseURL+"/monitors/:id", wrapper.UpdateMonitor, options.OperationMiddlewares["updateMonitor"]...)
	router.GET(options.BaseURL+"/monitors/:id/snapshots", wrapper.GetSnapshotsByMonitorID, options.OperationMiddlewares["getSnapshotsByMonitorID"]...)

}

type OauthCallbackRequestObject struct {
	Provider OauthCallbackParamsProvider `json:"provider"`
	Params   OauthCallbackParams
}

type OauthCallbackResponseObject interface {
	VisitOauthCallbackResponse(w http.ResponseWriter) error
}

type OauthCallback200ResponseHeaders struct {
	SetCookie *string
}

type OauthCallback200JSONResponse struct {
	Body    AuthResponse
	Headers OauthCallback200ResponseHeaders
}

func (response OauthCallback200JSONResponse) VisitOauthCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OauthCallback400JSONResponse ErrorResponse

func (response OauthCallback400JSONResponse) VisitOauthCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type OauthCallback401JSONResponse ErrorResponse

func (response OauthCallback401JSONResponse) VisitOauthCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200ResponseHeaders struct {
	SetCookie *string
}

type LoginUser200JSONResponse struct {
	Body    AuthResponse
	Headers LoginUser200ResponseHeaders
}

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser401JSONResponse ErrorResponse

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutUserRequestObject struct {
}

type LogoutUserResponseObject interface {
	VisitLogoutUserResponse(w http.ResponseWriter) error
}

type LogoutUser204ResponseHeaders struct {
	SetCookie *string
}

type LogoutUser204Response struct {
	Headers LogoutUser204ResponseHeaders
}

func (response LogoutUser204Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type LogoutUser401JSONResponse ErrorResponse

func (response LogoutUser401JSONResponse) VisitLogoutUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200ResponseHeaders struct {
	SetCookie *string
}

type RefreshToken200JSONResponse struct {
	Body    AuthResponse
	Headers RefreshToken200ResponseHeaders
}

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse ErrorResponse

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMonitorsRequestObject struct {
	Params GetMonitorsParams
}

type GetMonitorsResponseObject interface {
	VisitGetMonitorsResponse(w http.ResponseWriter) error
}

type GetMonitors200JSONResponse []MonitorResponse

func (response GetMonitors200JSONResponse) VisitGetMonitorsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMonitors401JSONResponse ErrorResponse

func (response GetMonitors401JSONResponse) VisitGetMonitorsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMonitorRequestObject struct {
	Body *CreateMonitorJSONRequestBody
}

type CreateMonitorResponseObject interface {
	VisitCreateMonitorResponse(w http.ResponseWriter) error
}

type CreateMonitor201JSONResponse MonitorResponse

func (response CreateMonitor201JSONResponse) VisitCreateMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMonitor401JSONResponse ErrorResponse

func (response CreateMonitor401JSONResponse) VisitCreateMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteMonitorRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteMonitorResponseObject interface {
	VisitDeleteMonitorResponse(w http.ResponseWriter) error
}

type DeleteMonitor204Response struct {
}

func (response DeleteMonitor204Response) VisitDeleteMonitorResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteMonitor401JSONResponse ErrorResponse

func (response DeleteMonitor401JSONResponse) VisitDeleteMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteMonitor403JSONResponse ErrorResponse

func (response DeleteMonitor403JSONResponse) VisitDeleteMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteMonitor404JSONResponse ErrorResponse

func (response DeleteMonitor404JSONResponse) VisitDeleteMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMonitorRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateMonitorJSONRequestBody
}

type UpdateMonitorResponseObject interface {
	VisitUpdateMonitorResponse(w http.ResponseWriter) error
}

type UpdateMonitor200JSONResponse MonitorResponse

func (response UpdateMonitor200JSONResponse) VisitUpdateMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMonitor401JSONResponse ErrorResponse

func (response UpdateMonitor401JSONResponse) VisitUpdateMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMonitor403JSONResponse ErrorResponse

func (response UpdateMonitor403JSONResponse) VisitUpdateMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMonitor404JSONResponse ErrorResponse

func (response UpdateMonitor404JSONResponse) VisitUpdateMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSnapshotsByMonitorIDRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params GetSnapshotsByMonitorIDParams
}

type GetSnapshotsByMonitorIDResponseObject interface {
	VisitGetSnapshotsByMonitorIDResponse(w http.ResponseWriter) error
}

type GetSnapshotsByMonitorID200JSONResponse []SnapshotResponse

func (response GetSnapshotsByMonitorID200JSONResponse) VisitGetSnapshotsByMonitorIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSnapshotsByMonitorID401JSONResponse ErrorResponse

func (response GetSnapshotsByMonitorID401JSONResponse) VisitGetSnapshotsByMonitorIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSnapshotsByMonitorID403JSONResponse ErrorResponse

func (response GetSnapshotsByMonitorID403JSONResponse) VisitGetSnapshotsByMonitorIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetSnapshotsByMonitorID404JSONResponse ErrorResponse

func (response GetSnapshotsByMonitorID404JSONResponse) VisitGetSnapshotsByMonitorIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse UserResponse

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUser409JSONResponse ErrorResponse

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateUserJSONRequestBody
}

type UpdateUserResponseObject interface {
	VisitUpdateUserResponse(w http.ResponseWriter) error
}

type UpdateUser200JSONResponse UserResponse

func (response UpdateUser200JSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser401JSONResponse ErrorResponse

func (response UpdateUser401JSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser403JSONResponse ErrorResponse

func (response UpdateUser403JSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser409JSONResponse ErrorResponse

func (response UpdateUser409JSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// OauthCallback OAuth callback handler
	// (GET /auth/callback/{provider})
	OauthCallback(ctx context.Context, request OauthCallbackRequestObject) (OauthCallbackResponseObject, error)
	// LoginUser Logs user into the system
	// (POST /auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// LogoutUser Revoke the current refresh token and end the session
	// (POST /auth/logout)
	LogoutUser(ctx context.Context, request LogoutUserRequestObject) (LogoutUserResponseObject, error)
	// RefreshToken Rotate the refresh token and issue a new access token
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// GetMonitors Get monitors for current user
	// (GET /monitors)
	GetMonitors(ctx context.Context, request GetMonitorsRequestObject) (GetMonitorsResponseObject, error)
	// CreateMonitor Add object to monitor
	// (POST /monitors)
	CreateMonitor(ctx context.Context, request CreateMonitorRequestObject) (CreateMonitorResponseObject, error)
	// DeleteMonitor Delete a monitor
	// (DELETE /monitors/{id})
	DeleteMonitor(ctx context.Context, request DeleteMonitorRequestObject) (DeleteMonitorResponseObject, error)
	// UpdateMonitor Update monitor configuration
	// (PATCH /monitors/{id})
	UpdateMonitor(ctx context.Context, request UpdateMonitorRequestObject) (UpdateMonitorResponseObject, error)
	// GetSnapshotsByMonitorID Get snapshots by monitor ID
	// (GET /monitors/{id}/snapshots)
	GetSnapshotsByMonitorID(ctx context.Context, request GetSnapshotsByMonitorIDRequestObject) (GetSnapshotsByMonitorIDResponseObject, error)
	// CreateUser Create user
	// (POST /user)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// UpdateUser Update user
	// (PATCH /user/{id})
	UpdateUser(ctx context.Context, request UpdateUserRequestObject) (UpdateUserResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// OauthCallback operation middleware
func (sh *strictHandler) OauthCallback(ctx echo.Context, provider OauthCallbackParamsProvider, params OauthCallbackParams) error {
	var request OauthCallbackRequestObject

	request.Provider = provider
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OauthCallback(ctx.Request().Context(), request.(OauthCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OauthCallback")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OauthCallbackResponseObject); ok {
		return validResponse.VisitOauthCallbackResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(ctx echo.Context) error {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx.Request().Context(), request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		return validResponse.VisitLoginUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LogoutUser operation middleware
func (sh *strictHandler) LogoutUser(ctx echo.Context) error {
	var request LogoutUserRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutUser(ctx.Request().Context(), request.(LogoutUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutUserResponseObject); ok {
		return validResponse.VisitLogoutUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx echo.Context) error {
	var request RefreshTokenRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx.Request().Context(), request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		return validResponse.VisitRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMonitors operation middleware
func (sh *strictHandler) GetMonitors(ctx echo.Context, params GetMonitorsParams) error {
	var request GetMonitorsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMonitors(ctx.Request().Context(), request.(GetMonitorsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMonitors")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMonitorsResponseObject); ok {
		return validResponse.VisitGetMonitorsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateMonitor operation middleware
func (sh *strictHandler) CreateMonitor(ctx echo.Context) error {
	var request CreateMonitorRequestObject

	var body CreateMonitorJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		if !errors.Is(err, io.EOF) {
			return err
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMonitor(ctx.Request().Context(), request.(CreateMonitorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMonitor")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateMonitorResponseObject); ok {
		return validResponse.VisitCreateMonitorResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteMonitor operation middleware
func (sh *strictHandler) DeleteMonitor(ctx echo.Context, id openapi_types.UUID) error {
	var request DeleteMonitorRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteMonitor(ctx.Request().Context(), request.(DeleteMonitorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteMonitor")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteMonitorResponseObject); ok {
		return validResponse.VisitDeleteMonitorResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateMonitor operation middleware
func (sh *strictHandler) UpdateMonitor(ctx echo.Context, id openapi_types.UUID) error {
	var request UpdateMonitorRequestObject

	request.Id = id

	var body UpdateMonitorJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMonitor(ctx.Request().Context(), request.(UpdateMonitorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMonitor")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateMonitorResponseObject); ok {
		return validResponse.VisitUpdateMonitorResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSnapshotsByMonitorID operation middleware
func (sh *strictHandler) GetSnapshotsByMonitorID(ctx echo.Context, id openapi_types.UUID, params GetSnapshotsByMonitorIDParams) error {
	var request GetSnapshotsByMonitorIDRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSnapshotsByMonitorID(ctx.Request().Context(), request.(GetSnapshotsByMonitorIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSnapshotsByMonitorID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetSnapshotsByMonitorIDResponseObject); ok {
		return validResponse.VisitGetSnapshotsByMonitorIDResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(ctx echo.Context) error {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		if !errors.Is(err, io.EOF) {
			return err
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx.Request().Context(), request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		return validResponse.VisitCreateUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUser operation middleware
func (sh *strictHandler) UpdateUser(ctx echo.Context, id openapi_types.UUID) error {
	var request UpdateUserRequestObject

	request.Id = id

	var body UpdateUserJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUser(ctx.Request().Context(), request.(UpdateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserResponseObject); ok {
		return validResponse.VisitUpdateUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
