// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Monitor struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Url             string
	Active          bool
	PollIntervalSec int32
	CheckedAt       time.Time
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	IssuedAt   pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	ReplacedBy pgtype.UUID
}

type Snapshot struct {
	ID             uuid.UUID
	MonitorID      uuid.UUID
	CheckedAt      time.Time
	Alive          bool
	StatusCode     int16
	ResponseTimeMs int32
	ResponseSize   int64
	ServerName     string
	SslExpiresAt   *time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
}
