// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (id, user_id, url, active, poll_interval_sec)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, url, active, poll_interval_sec, checked_at
`

type CreateMonitorParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Url             string
	Active          bool
	PollIntervalSec int32
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.Active,
		arg.PollIntervalSec,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Active,
		&i.PollIntervalSec,
		&i.CheckedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors
WHERE id = $1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonitor, id)
	return err
}

const getMonitorByUserID = `-- name: GetMonitorByUserID :many
SELECT id, user_id, url, active, poll_interval_sec, checked_at
FROM monitors
WHERE user_id = $1
ORDER BY checked_at DESC
LIMIT $2 OFFSET $3
`

type GetMonitorByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetMonitorByUserID(ctx context.Context, arg GetMonitorByUserIDParams) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, getMonitorByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Active,
			&i.PollIntervalSec,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitor = `-- name: UpdateMonitor :exec
UPDATE monitors
SET url = $2,
    active = $3,
    poll_interval_sec = $4
WHERE id = $1
`

type UpdateMonitorParams struct {
	ID              uuid.UUID
	Url             string
	Active          bool
	PollIntervalSec int32
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) error {
	_, err := q.db.Exec(ctx, updateMonitor,
		arg.ID,
		arg.Url,
		arg.Active,
		arg.PollIntervalSec,
	)
	return err
}
