// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteExpiredSessions(ctx context.Context, revokedAt pgtype.Timestamptz) error
	DeleteMonitor(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetMonitorByUserID(ctx context.Context, arg GetMonitorByUserIDParams) ([]Monitor, error)
	GetSessionByHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetSnapshotsByMonitorID(ctx context.Context, arg GetSnapshotsByMonitorIDParams) ([]Snapshot, error)
	GetUSerByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RotateSession(ctx context.Context, arg RotateSessionParams) error
	UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
