// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (
    id, monitor_id, alive, status_code, response_time_ms, response_size, server_name, ssl_expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, monitor_id, checked_at, alive, status_code, response_time_ms, response_size, server_name, ssl_expires_at
`

type CreateSnapshotParams struct {
	ID             uuid.UUID
	MonitorID      uuid.UUID
	Alive          bool
	StatusCode     int16
	ResponseTimeMs int32
	ResponseSize   int64
	ServerName     string
	SslExpiresAt   *time.Time
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot,
		arg.ID,
		arg.MonitorID,
		arg.Alive,
		arg.StatusCode,
		arg.ResponseTimeMs,
		arg.ResponseSize,
		arg.ServerName,
		arg.SslExpiresAt,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.CheckedAt,
		&i.Alive,
		&i.StatusCode,
		&i.ResponseTimeMs,
		&i.ResponseSize,
		&i.ServerName,
		&i.SslExpiresAt,
	)
	return i, err
}

const getSnapshotsByMonitorID = `-- name: GetSnapshotsByMonitorID :many
SELECT id, monitor_id, checked_at, alive, status_code, response_time_ms, response_size, server_name, ssl_expires_at
FROM snapshots
WHERE monitor_id = $1
ORDER BY checked_at DESC
LIMIT $2 OFFSET $3
`

type GetSnapshotsByMonitorIDParams struct {
	MonitorID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) GetSnapshotsByMonitorID(ctx context.Context, arg GetSnapshotsByMonitorIDParams) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, getSnapshotsByMonitorID, arg.MonitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.CheckedAt,
			&i.Alive,
			&i.StatusCode,
			&i.ResponseTimeMs,
			&i.ResponseSize,
			&i.ServerName,
			&i.SslExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
