// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OauthCallbackParamsProvider.
const (
	Github OauthCallbackParamsProvider = "github"
	Google OauthCallbackParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the OauthCallbackParamsProvider enum.
func (e OauthCallbackParamsProvider) Valid() bool {
	switch e {
	case Github:
		return true
	case Google:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken The JWT access token to be used in the Authorization header
	AccessToken string `json:"accessToken"`

	// ExpiresIn Access token lifetime in seconds. The refresh token's lifetime is not exposed here — it lives in the HttpOnly cookie's Max-Age.
	ExpiresIn *int `json:"expiresIn,omitempty"`

	// TokenType The type of the token issued
	TokenType string `json:"tokenType"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Stable, machine-readable error code — switch on this, not on the HTTP status text.
	Code string `json:"code"`

	// Details Optional structured context, e.g. which fields failed validation and why. Omitted when there's nothing more specific to add.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable explanation, safe to display or log.
	Message string `json:"message"`

	// Timestamp When the server produced this error.
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// TraceId Correlates this response with the matching server-side log entry. Include it when reporting a bug.
	TraceId *string `json:"traceId,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MonitorCreateRequest defines model for MonitorCreateRequest.
type MonitorCreateRequest struct {
	PollIntervalSec *int   `json:"pollIntervalSec,omitempty"`
	Url             string `json:"url"`
}

// MonitorResponse defines model for MonitorResponse.
type MonitorResponse struct {
	Active          bool               `json:"active"`
	CheckedAt       time.Time          `json:"checkedAt"`
	Id              openapi_types.UUID `json:"id"`
	PollIntervalSec int                `json:"pollIntervalSec"`
	Url             string             `json:"url"`
}

// MonitorUpdateRequest defines model for MonitorUpdateRequest.
type MonitorUpdateRequest struct {
	Active          bool   `json:"active"`
	PollIntervalSec int    `json:"pollIntervalSec"`
	Url             string `json:"url"`
}

// SnapshotResponse defines model for SnapshotResponse.
type SnapshotResponse struct {
	Alive          bool               `json:"alive"`
	CheckedAt      time.Time          `json:"checkedAt"`
	Id             openapi_types.UUID `json:"id"`
	MonitorId      openapi_types.UUID `json:"monitorId"`
	ResponseSize   int                `json:"responseSize"`
	ResponseTimeMs int                `json:"responseTimeMs"`
	ServerName     *string            `json:"serverName,omitempty"`
	SslExpiresAt   *time.Time         `json:"sslExpiresAt,omitempty"`
	StatusCode     int                `json:"statusCode"`
}

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
}

// UserUpdateRequest defines model for UserUpdateRequest.
type UserUpdateRequest struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Password *string              `json:"password,omitempty"`
}

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// ConflictError defines model for ConflictError.
type ConflictError = ErrorResponse

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorResponse

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ErrorResponse

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	// Code Temporary authorization code from the OAuth provider
	Code string `form:"code" json:"code"`

	// State Security string
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// OauthCallbackParamsProvider defines parameters for OauthCallback.
type OauthCallbackParamsProvider string

// GetMonitorsParams defines parameters for GetMonitors.
type GetMonitorsParams struct {
	// Limit Maximum number of monitors to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of monitors to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetSnapshotsByMonitorIDParams defines parameters for GetSnapshotsByMonitorID.
type GetSnapshotsByMonitorIDParams struct {
	// Limit Maximum number of snapshots to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of snapshots to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// CreateMonitorJSONRequestBody defines body for CreateMonitor for application/json ContentType.
type CreateMonitorJSONRequestBody = MonitorCreateRequest

// UpdateMonitorJSONRequestBody defines body for UpdateMonitor for application/json ContentType.
type UpdateMonitorJSONRequestBody = MonitorUpdateRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreateRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// OauthCallback OAuth callback handler
	// (GET /auth/callback/{provider})
	OauthCallback(ctx echo.Context, provider OauthCallbackParamsProvider, params OauthCallbackParams) error
	// LoginUser Logs user into the system
	// (POST /auth/login)
	LoginUser(ctx echo.Context) error
	// LogoutUser Revoke the current refresh token and end the session
	// (POST /auth/logout)
	LogoutUser(ctx echo.Context) error
	// RefreshToken Rotate the refresh token and issue a new access token
	// (POST /auth/refresh)
	RefreshToken(ctx echo.Context) error
	// GetMonitors Get monitors for current user
	// (GET /monitors)
	GetMonitors(ctx echo.Context, params GetMonitorsParams) error
	// CreateMonitor Add object to monitor
	// (POST /monitors)
	CreateMonitor(ctx echo.Context) error
	// DeleteMonitor Delete a monitor
	// (DELETE /monitors/{id})
	DeleteMonitor(ctx echo.Context, id openapi_types.UUID) error
	// UpdateMonitor Update monitor configuration
	// (PATCH /monitors/{id})
	UpdateMonitor(ctx echo.Context, id openapi_types.UUID) error
	// GetSnapshotsByMonitorID Get snapshots by monitor ID
	// (GET /monitors/{id}/snapshots)
	GetSnapshotsByMonitorID(ctx echo.Context, id openapi_types.UUID, params GetSnapshotsByMonitorIDParams) error
	// CreateUser Create user
	// (POST /user)
	CreateUser(ctx echo.Context) error
	// UpdateUser Update user
	// (PATCH /user/{id})
	UpdateUser(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// OauthCallback converts echo context to params.
func (w *ServerInterfaceWrapper) OauthCallback(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "provider" -------------
	var provider OauthCallbackParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", ctx.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OauthCallbackParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", ctx.QueryParams(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", ctx.QueryParams(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OauthCallback(ctx, provider, params)
	return err
}

// LoginUser converts echo context to params.
func (w *ServerInterfaceWrapper) LoginUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LoginUser(ctx)
	return err
}

// LogoutUser converts echo context to params.
func (w *ServerInterfaceWrapper) LogoutUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LogoutUser(ctx)
	return err
}

// RefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshToken(ctx)
	return err
}

// GetMonitors converts echo context to params.
func (w *ServerInterfaceWrapper) GetMonitors(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMonitorsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMonitors(ctx, params)
	return err
}

// CreateMonitor converts echo context to params.
func (w *ServerInterfaceWrapper) CreateMonitor(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateMonitor(ctx)
	return err
}

// DeleteMonitor converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteMonitor(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteMonitor(ctx, id)
	return err
}

// UpdateMonitor converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateMonitor(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateMonitor(ctx, id)
	return err
}

// GetSnapshotsByMonitorID converts echo context to params.
func (w *ServerInterfaceWrapper) GetSnapshotsByMonitorID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSnapshotsByMonitorIDParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSnapshotsByMonitorID(ctx, id, params)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUser(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/user", wrapper.CreateUser, options.OperationMiddlewares["createUser"]...)
	router.PATCH(options.BaseURL+"/user/:id", wrapper.UpdateUser, options.OperationMiddlewares["updateUser"]...)
	router.POST(options.BaseURL+"/auth/login", wrapper.LoginUser, options.OperationMiddlewares["loginUser"]...)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken, options.OperationMiddlewares["refreshToken"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.LogoutUser, options.OperationMiddlewares["logoutUser"]...)
	router.GET(options.BaseURL+"/auth/callback/:provider", wrapper.OauthCallback, options.OperationMiddlewares["oauthCallback"]...)
	router.GET(options.BaseURL+"/monitors", wrapper.GetMonitors, options.OperationMiddlewares["getMonitors"]...)
	router.POST(options.BaseURL+"/monitors", wrapper.CreateMonitor, options.OperationMiddlewares["createMonitor"]...)
	router.DELETE(options.BaseURL+"/monitors/:id", wrapper.DeleteMonitor, options.OperationMiddlewares["deleteMonitor"]...)
	router.PATCH(options.BaseURL+"/monitors/:id", wrapper.UpdateMonitor, options.OperationMiddlewares["updateMonitor"]...)
	router.GET(options.BaseURL+"/monitors/:id/snapshots", wrapper.GetSnapshotsByMonitorID, options.OperationMiddlewares["getSnapshotsByMonitorID"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fv9ctu2ln8VLHdnbjtDSZT8kViZztS1E1du/VHLvrl7ez0tRBxJiEmABUDLakYz+xD7hPskOwcAKVGi",
	"JKdx4my3/5kUARz8zu98An4fxDLNpABhdNB9HyjQmRQa7MN3lF3Bbzlo81opqfBVLIUBYfBPmmUJj6nh",
	"UrTeaSnwnY7HkFL86z8UDINu8O+t+fwt96tu2dmu/ErBbDYLAwY6VjzDyYJucD0GotzKZEI1SWkylCoF",
	"RqQiQ8oTYOSeJpzZ1ZvBLAyOpBgmPH5OSWMvgiYTbsbEjIHEuVIgDNGGGiByaF8q0DJXMVi530g14IyB",
	"+MyCH+ZmDMLg7MBCMsgNEdKQDFTKjQFGjMQHhJ2YMdeExiXWPWFACZr0Qd2D+tyCC5ILeMggRikBPycy",
	"tkAzMhnzBEimZAxaczEiZq4fK/q5NG9kLtjz0QRYSQDCJGgLOzxwL+CNoLkZS8V/h88t5Bm3mIWEC2tc",
	"IVobPGQckY0VMOQLTXQzwLF+WlwVuVRO3H0fZEpmoAx3XoTGqIxreQdW2FVgTt9eE/cRMfgVUm8AJNfA",
	"CBdWhYceE7tvMgbKQAVhAA80zRIIugFMT8eDk5hf8NPeze+99jnv6Z642ouPevu9u+wffz86PWjC9PR3",
	"9rbHL3jv4ezdWXR+/Z87F8d3kx6f8EH6xvyzbz++pye7o6uTgwTf07dvot47+XB+/bpz9u5s7+y4Nx3+",
	"1OwPkx8eJlen/TP44Yc3nZ+ud4eT7AxOhzv7lxd3+9PTv/9C2U9aT/biIAzMNEMhtVFcjFDLDlXdq0Hk",
	"cBGJhA/B8BQQBw2xFEw3iSPTUIEeu8/+phc+LAiVScRvDArI//zXfxNuSMLvQReIfm9MdiGSKYmlvOPw",
	"N03O6EPjcATNRVwPoqiUngsDI1Aovl312r6uUygOKJyd2wfXOgdW0dh3QJVV4hI4szBAS0HSBd2fK+xZ",
	"XPi2HCgH7yA2KFaV4StEjCWrEbhv6CCBkKQ0HnMBDQWU4RvvWnCQBVBPuInHRArrDkOLsvRYXl9fWhef",
	"a2LgwTSrGz08/uXq9U83r/vXdVRgYChPnKUwxlEqmlwuCG5UDsumepG574g2Ko9Nbi1UClw8JNAcNdET",
	"xmMy5JAwvRoyCRXoLKdNcuHd/WQMdjMKqSCkGaP3TKUCojOI+ZDHaJaUsWZQg3wKWtNRDbrf5ykVC5g+",
	"ZAkVVoSQaDpEfhDGdZbQKXqbRI6q4FmVEj89KbCqgRHJrw1Ns1UZ3vqtEW3jFYYHlsfAXFyzaq4u2ok6",
	"+43ooNF5cd2Ouu29bhT9MwgDjIXUBN2AUQMNXLBWEEVj6LFVMY6kUpBQA9otXKRa82whpSa2uDtBG5oz",
	"QEgICKOmTdITcZIzQFu26lKQSWVwACWDfAm5wQ5rw/4gauxDhzZ2By8HjYN4BxoRbQ87g514l+3BVuuz",
	"JjNXb53R/ShHXPg0cdXmIKU8sX+Ugr2TY/Gtfd+MZbqIq/s4DFL68COIkRkH3c7eXg3GGdV6IhWrTtyH",
	"WIG5/Fbrdmdncd7y8zBIuSimfrlt84U45fC67Z9JwY1URwqogbUwZDJJbNZ0j1lT7MgxpHligu4O+thy",
	"Fzv1HjdXSyiOjcl0t9VKp8iBoUy4XIYzV3yrgnHeDdvaFNUNv4eKTM5R+akGUiZABc4VjyG+A3Zoqjso",
	"rWznut3pRtEHWRlf0v2LwQHs7u2/aMDLg0Gj3WE7Dbq7t9/Y7ezvt3fbL3ajKKpgk3NWN2+Nop5LNVZA",
	"nDwswF4VbxHcDWq8ydgmdn6ALp8Wn4aASYPJlHLxR8m7AZw6QPqCZnoszQZiJ18Srw+GLzfz+uDg4DG8",
	"Th0Rep/IbIpY1ue/V7Hb3evUkqIYcM1TONOVIe3dvboRLiae07S6QCBGXDy02s3OXrMdhIHIk4QOVtQ2",
	"F1Xr5LXLvmsU96IRtRvtveso2qK47cvYdPDIp5zlIp0oWju43GydI5grcJF4oadrZb0VdJf0U2cXNxq2",
	"xbA/fShHDNb7hU+z/U8Tx+oI5ERat+8tEaJm8wImv9jX3/p3T0yBc5j08wyUo0K7s/Nvf5AHS/u1riTO",
	"FTfTPrYwfKvTVqPYZsCngX16Uyx2+hYrtw1luq0Px1KZBlojsx0NDcIQqsmvld5Fl7iVyL/yKNqJ7XD7",
	"J/wa+J6KjTJLxTGGTITqhJvv88FFIWdVpJ5w8LjKUGJxbwWjKRDlXwOKdCLlKAE7C6EDeW9r/mEiJy4A",
	"LspbOLDKyxuVeJkwjI+4GecD1H4rwVqgJfHjVjHCOqdYZuD7y5R1cw0KuatBEUYN9d2fILSvup5s7nf7",
	"UHxQtB4eJ4Ad84sdUCEC/tqxaM5xeAyaTXJsvxjYCg4IIub+ULY/x7BlhZQgChhXEBv7q92GkR71ohnj",
	"+zQKhqBAYDWKXCmY+SuxNfqUoBEWTS8FIRlATHMNroI8vOwRAVjSKojBdneoX6bhOi6en06aZPoKV7bE",
	"KAeghBXluo7HPafk5PU1sWpsxTRJBjS+a43s5M1/iY8hDI1jmQujm342VJx0Suu07jt2yQpp1hMiDGQG",
	"Ap1ocJGB6B2TIykEIs9tt3LoW6VBGGRKDnkCxTSLvKunlRPIC0kzrq2gG+h05Xpytld1ZLtqq6z6UYqR",
	"cxIhkRn9LV9q5RFtJDZzFjsAX42pHgP72jZtGOBo5fhCRdnHC0kfuQMh6dMU+tyA7+w1ybmlSNERNJKc",
	"0nvat0IRidwxuRKu10rJaf/inAwkmzbJDX5u2TKYeiIUsqIk7k0iRzI3jhEcd+hWDcJA2FQt8EO8HZaw",
	"0Yz/AFPXhuZiKIs2N43NosplAqM7+rKz8+2ojLOrRwKXPTKUilAygYHGreeZbYb6pKloqfAY5TLcWBpc",
	"cjEChUYUhME9KO0mazejZhTMHLNoxoNusNNsNyObPZixJeSSVbzPlLznDNQMfxyB3UFpuT3LThxx5AfY",
	"qRRNwYDSQffnZZJc+umIhdDjiovPUS1WDBYjvcsm56cBIPIU47+jcBAGzlMGtzVhcqWPC2kmFVXTOu8w",
	"VDK1nsPFkAVhrKi/5aCmc1njIildK2cZ9Hdb0eHwVI7/kTabzeARYva9wyT+k3oJ7PFbsLjk8sS3YfXo",
	"sxNFT3bwUjkeqTl36efWDQ3zJHFol+dy1g1bjJvk2nlyZ/5T1ysEPbdCLhAwdzRit9AH01jnhsruf9X5",
	"ONslX2kAq95Vj0Z0CTjuDr7eiCrudTeK1gFUIt5aPmm249rbx62els3CYO8xK9adYaK4Ok9TqqZospbb",
	"hZGTMRUscTkZHWl7NIFx6hYHLSjBdft0jQuwjVLMtb0tgDbfSTZ9MppVGrGz2WzZ4mZfJMXdcVbl+I/r",
	"SkxCImJAemX/qhKWa6LBLIXCIvA9uznM/VolCH7TbDZfldK+8oH7VRm4v+kbxWPzilxSM/7GcutVcTr3",
	"TWfvoONqwD+Vsf0oR9plylwYadHWU20g3WxvMjcbDU7mprS4CvV361Kz0QgTntwQvUDXOtp5YnBN4gSo",
	"AvZ4qh3hAL1+zq8KRUePca3PozXPeZu51CW9P9/ObheVewX38g4qF2Kqe8d0Eusnq3bQ2mXs6/Tux65X",
	"/KJMwTN6vXOY+A1mlCt/CO74JBO26sr8vQsb+RESSgRMiBSw6Oc+3LudwwRdmzR24o2+7rGU+zwXUq4q",
	"EqbF9RR/JSUkyvLK3VOhCbYWpu7WyFeZ1JrjgbMZw9DYmtsooIbQJCkYpm3NYAtp63ioJiikkinXwL5+",
	"BjOxGqpxDcgFSx7PiMVoWW8nvvDRa+uREzBnxTdbqpEz+sDTPCUiTweg8F5HMbtrdWCkXpN3JzzlpsKp",
	"8tSzvXjoiQ+pWwYfItvU80917fEVhteKpu94ZnWc0REXRR+gTk45HGpYI+iinJ1FyWrONT66jOAGUr3N",
	"bpbPZue9CKoUndZemiswAEYSrg1CZUlfEuX/YPKwaF+L/dtluzoBM+cF8qEIQrmu5PPFN8HtLFwTWdwR",
	"iVfAJ8rja28UzHxCX+FW+6nX3Hg70H1SyY1IbIVkf2b2HDJG3NkB+pS0VH0NaxY9b+s9ZzPnSBIwsEql",
	"Y/t+TqWNPvhGcGwV3tz0jouLdX4hFMovUdso4szTdFvr5YlOnm4fk2rXcsnt4pm4tBvtbB+5dFfbDtvd",
	"Pqx65/izEdcRjNDNnLVdzXi8yk93Ivgk/MztVF8QPz+Z064eo27wov5i5iI4n69b8wHe3knHKpb6l4U+",
	"kYU6tpSWgv8/wke5KjLVx0SYlvYXmjam+sWtJ/3d1Cu2d/xxJj0EvAxdLo5p1Zdh3+H28mUu9UfUL52V",
	"uuBJ6peKbFjAfGTF8kUULCuX7v5gxTLn+l8e6OlKoznlBtPSxHvH6x2Qu77xfmOJ9AnPOVavqn3i4qhy",
	"L6yGqvj701RCB9vHVf/P8eka8A7R5ZLYPs61XhY1G3NGr/vN0WUhrPg1Pzx4PFOut3pf7jOftj2KkP9P",
	"M7fnMKIPzPfW2NisfPV+5b+9vJFpvK6XG9+6o4KOILXXDAVbPFV16aO3ITv9LNw6J44vRPND8dVjhvr4",
	"AEWjRM+nmPcXb2f/OwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
