// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Monitor struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Url             string
	Tracked         bool
	PollIntervalSec int32
	CheckedAt       pgtype.Timestamptz
}

type Snapshot struct {
	ID             uuid.UUID
	MonitorID      uuid.UUID
	CheckedAt      pgtype.Timestamptz
	IsUp           bool
	StatusCode     int16
	ResponseTimeMs int32
	ResponseSize   int64
	ServerName     string
	SslExpiresAt   pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
}
