// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createWebsite = `-- name: CreateWebsite :one
INSERT INTO monitors (id, user_id, url, tracked, poll_interval_sec)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, url, tracked, poll_interval_sec, checked_at
`

type CreateWebsiteParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Url             string
	Tracked         bool
	PollIntervalSec int32
}

func (q *Queries) CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createWebsite,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.Tracked,
		arg.PollIntervalSec,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Tracked,
		&i.PollIntervalSec,
		&i.CheckedAt,
	)
	return i, err
}

const deleteWebsite = `-- name: DeleteWebsite :exec
DELETE FROM monitors
WHERE id = $1
`

func (q *Queries) DeleteWebsite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebsite, id)
	return err
}

const getWebsitesByUserID = `-- name: GetWebsitesByUserID :many
SELECT id, user_id, url, tracked, poll_interval_sec, checked_at
FROM monitors
WHERE user_id = $1
`

func (q *Queries) GetWebsitesByUserID(ctx context.Context, userID uuid.UUID) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, getWebsitesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Tracked,
			&i.PollIntervalSec,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebsite = `-- name: UpdateWebsite :exec
UPDATE monitors
SET url = $2,
    tracked = $3,
    poll_interval_sec = $4
WHERE id = $1
`

type UpdateWebsiteParams struct {
	ID              uuid.UUID
	Url             string
	Tracked         bool
	PollIntervalSec int32
}

func (q *Queries) UpdateWebsite(ctx context.Context, arg UpdateWebsiteParams) error {
	_, err := q.db.Exec(ctx, updateWebsite,
		arg.ID,
		arg.Url,
		arg.Tracked,
		arg.PollIntervalSec,
	)
	return err
}
