// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (Monitor, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteWebsite(ctx context.Context, id uuid.UUID) error
	FindByEmail(ctx context.Context, email string) (User, error)
	FindByID(ctx context.Context, id uuid.UUID) (User, error)
	GetSnapshotsByWebsiteID(ctx context.Context, arg GetSnapshotsByWebsiteIDParams) ([]Snapshot, error)
	GetWebsitesByUserID(ctx context.Context, userID uuid.UUID) ([]Monitor, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateWebsite(ctx context.Context, arg UpdateWebsiteParams) error
}

var _ Querier = (*Queries)(nil)
