// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (
    id, monitor_id, is_up, status_code, response_time_ms, response_size, server_name, ssl_expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, monitor_id, checked_at, is_up, status_code, response_time_ms, response_size, server_name, ssl_expires_at
`

type CreateSnapshotParams struct {
	ID             uuid.UUID
	MonitorID      uuid.UUID
	IsUp           bool
	StatusCode     int16
	ResponseTimeMs int32
	ResponseSize   int64
	ServerName     string
	SslExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot,
		arg.ID,
		arg.MonitorID,
		arg.IsUp,
		arg.StatusCode,
		arg.ResponseTimeMs,
		arg.ResponseSize,
		arg.ServerName,
		arg.SslExpiresAt,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.CheckedAt,
		&i.IsUp,
		&i.StatusCode,
		&i.ResponseTimeMs,
		&i.ResponseSize,
		&i.ServerName,
		&i.SslExpiresAt,
	)
	return i, err
}

const getSnapshotsByWebsiteID = `-- name: GetSnapshotsByWebsiteID :many
SELECT id, monitor_id, checked_at, is_up, status_code, response_time_ms, response_size, server_name, ssl_expires_at
FROM snapshots
WHERE monitor_id = $1
ORDER BY checked_at DESC
LIMIT $2
`

type GetSnapshotsByWebsiteIDParams struct {
	MonitorID uuid.UUID
	Limit     int32
}

func (q *Queries) GetSnapshotsByWebsiteID(ctx context.Context, arg GetSnapshotsByWebsiteIDParams) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, getSnapshotsByWebsiteID, arg.MonitorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.CheckedAt,
			&i.IsUp,
			&i.StatusCode,
			&i.ResponseTimeMs,
			&i.ResponseSize,
			&i.ServerName,
			&i.SslExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
